require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Override Firebase SDK Version
$FirebaseSDKVersion = '7.0.0'
platform :ios, '10.0'

target 'Clicks' do

  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  config = use_native_modules!


  use_react_native!(:path => config["reactNativePath"])

  # add the Firebase pod for Google Analytics
  pod 'FirebaseAnalytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'






  target 'ClicksTests' do
    inherit! :complete
    # Pods for testing
  end


  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end

target 'Clicks-tvOS' do
  # Pods for Clicks-tvOS

  target 'Clicks-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
