export const SET_USER = 'SET_USER';
export const SET_USERDATA = 'SET_USERDATA';
export const SET_USERPHOTO = 'SET_USERPHOTO';
export const SET_STATUS = 'SET_STATUS';
export const SET_LASTSEEN = 'SET_LASTSEEN';
export const SET_CONTACTS = 'SET_CONTACTS';

export const SET_STARTLOADING = 'SET_STARTLOADING';
export const SET_STOPLOADING = 'SET_STOPLOADING';

export const SET_SIGNINERROR = 'SET_SIGNINERROR';
export const SET_SIGNINDONE = 'SET_SIGNINDONE';
export const SET_RESULT = 'SET_RESULT';

export const SET_CODECONFIRMATIONERROR = 'SET_CODECONFIRMATIONERROR';
export const SET_CODECONFIRMATIONDONE = 'SET_CODECONFIRMATIONDONE';

export const SET_FIRSTTIMESTART = 'SET_FIRSTTIMESTART';
export const SET_FIRSTTIMESTOP = 'SET_FIRSTTIMESTOP';

export const SET_USER2 = 'SET_USER2';

//chatAction

export const SET_CONVERSATIONS_LENGTH = 'SET_CONVERSATIONS_LENGTH';
export const SET_CONVERSATIONS = 'SET_CONVERSATIONS';

export const SET_CHAT_LENGTH = 'SET_CHAT_LENGTH';
export const SET_CHAT = 'SET_CHAT';

export const SET_VIBES_LENGTH = 'SET_VIBES_LENGTH';

export const SET_FCM_TOKEN = 'SET_FCM_TOKEN';

export const SET_BLOCKED_USERS = 'SET_BLOCKED_USERS';

export const SET_CONTACTS_ACTIVE = 'SET_CONTACTS_ACTIVE';